[#1] Minor static analysis issues

diff --git a/virtfatfs-create b/virtfatfs-create
--- a/virtfatfs-create
+++ b/virtfatfs-create
@@ -1,13 +1,11 @@
 #!/bin/bash
 
-export TOP_DIR="$(cd "$(dirname "$(which "$0")")" ; pwd -P)"
-
-cd ${TOP_DIR}
+export TOP_DIR="$(cd "$(dirname "$(command -v "$0")")" ; pwd -P)"
 
 function fail()
 {
 	if [ $# -ne 0 ] ; then
-		echo $@ >&2
+		echo "$@" >&2
 	fi
 	exit 1
 }
@@ -15,7 +13,7 @@ function fail()
 function usage()
 {
 	if [ $# -ne 0 ] ; then
-		echo $@ >&2
+		echo "$@" >&2
 	fi
 	echo "Usage: $0 data_dir img_file img_size" >&2
 	echo "Create a FATFS image with given content and size" >&2
@@ -29,6 +27,8 @@ function usage()
 	fail
 }
 
+cd "${TOP_DIR}" || fail "Failed to change directory"
+
 data_dir="$1"
 img_file="$2"
 img_size="$3"
@@ -37,7 +37,7 @@ if [ "$1" == "" ] ; then
 	usage
 fi
 
-if [ ! -d ${data_dir} ] ; then
+if [ ! -d "${data_dir}" ] ; then
 	usage "Directory is missing: ${data_dir}"
 fi
 
@@ -50,9 +50,9 @@ if [ "${img_size}" == "" ] ; then
 	usage "Image size is not set"
 fi
 
-which udisksctl > /dev/null || fail "udisksctl is not installed"
-which rsync > /dev/null || fail "rsync is not installed"
-which sync > /dev/null || fail "sync is not installed"
+command -v udisksctl > /dev/null || fail "udisksctl is not installed"
+command -v rsync > /dev/null || fail "rsync is not installed"
+command -v sync > /dev/null || fail "sync is not installed"
 
 dd if=/dev/zero "of=${img_file}" "count=${img_size}" bs=1M \
 	> /dev/null 2> /dev/null \
@@ -62,8 +62,8 @@ mkfs.fat "${img_file}" \
 	|| fail "Failed to create FAT image"
 
 result=$(./virtfatfs-mount "${img_file}" rw)
-media="$(echo $result | awk '{print $1}')"
-loop="$(echo $result | awk '{print $2}')"
+media="$(echo "$result" | awk '{print $1}')"
+loop="$(echo "$result" | awk '{print $2}')"
 
 function cleanup() {
   result=$?
@@ -75,5 +75,5 @@ trap cleanup EXIT ERR
 
 echo "Media: $media"
 echo "Loop:  $loop"
-rsync --progress --recursive --executability --times ${data_dir}/* "${media}/"
+rsync --progress --recursive --executability --times "${data_dir}"/* "${media}/"
 sync "${media}/"
diff --git a/virtfatfs-unmount b/virtfatfs-unmount
--- a/virtfatfs-unmount
+++ b/virtfatfs-unmount
@@ -1,13 +1,11 @@
 #!/bin/bash
 
-export TOP_DIR="$(cd "$(dirname "$(which "$0")")" ; pwd -P)"
-
-cd ${TOP_DIR}
+export TOP_DIR="$(cd "$(dirname "$(command -v "$0")")" ; pwd -P)"
 
 function fail()
 {
 	if [ $# -ne 0 ] ; then
-		echo $@ >&2
+		echo "$@" >&2
 	fi
 	exit 1
 }
@@ -15,7 +13,7 @@ function fail()
 function usage()
 {
 	if [ $# -ne 0 ] ; then
-		echo $@ >&2
+		echo "$@" >&2
 	fi
 	echo "Usage: $0 data_dir img_file img_size" >&2
 	echo "Create a FATFS image with given content and size" >&2
@@ -29,15 +27,17 @@ function usage()
 	fail
 }
 
+cd "${TOP_DIR}" || fail "Failed to change directory"
+
 loop="$1"
 
 if [ "${loop}" == "" ] ; then
 	usage "Loop device is not set"
 fi
 
-which udisksctl > /dev/null || fail "udisksctl is not installed"
-which rsync > /dev/null || fail "rsync is not installed"
-which sync > /dev/null || fail "sync is not installed"
+command -v udisksctl > /dev/null || fail "udisksctl is not installed"
+command -v rsync > /dev/null || fail "rsync is not installed"
+command -v sync > /dev/null || fail "sync is not installed"
 
 env LC_ALL=C.UTF-8 udisksctl unmount --block-device "${loop}" \
 	|| fail "Failed to unmount image"
